name: Update Contributors HTML
on:
  push:
    paths:
      - 'Contributors.md'
    branches:
      - main 

jobs:
  update-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Update index.html
        run: |
          import re
          
          # Read Contributors.md
          with open('Contributors.md', 'r') as f:
              contributors = re.findall(r'\[(.+?)\]', f.read())
          
          # Read index.html
          with open('index.html', 'r') as f:
              html_content = f.read()
          
          # Create new card divs
          new_cards = '\n'.join([f'      <div class="card">{name}</div>' for name in contributors])
          
          # Replace existing cards with new ones
          updated_html = re.sub(
              r'<div class="grid">.*?</div>',
              f'<div class="grid">\n{new_cards}\n    </div>',
              html_content,
              flags=re.DOTALL
          )
          
          # Write updated content back to index.html
          with open('index.html', 'w') as f:
              f.write(updated_html)
        shell: python

      - name: Commit and push if changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add index.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update contributors in index.html" && git push)